webmention_io.rb

Was causing `Liquid Exception: undefined method 'find_converter_instance' for nil:NilClass in _includes/post/webmentions.html, included in _layouts/post.html` due to using `@site` where it should have been `site`.

Fix @site -> site

---

README.md

Another little typo

---

jekyll-webmention_io.gemspec
lib/jekyll/generators/compile_js.rb
lib/jekyll/webmention_io.rb
spec/spec_helper.rb

Inspired by https://bogdanvlviv.github.io/posts/ruby/with-__dir__-we-can-restore-order-in-the-universe.html
/cc @bogdanvlviv

Define path with __dir__

---

jekyll-webmention_io.gemspec

fix #78
This should prevent conflicts with `jekyll-assets`

(deps) Bump uglifier to 4.x

---

lib/jekyll/tags/bookmarks.rb
lib/jekyll/tags/count.rb
lib/jekyll/tags/likes.rb
lib/jekyll/tags/links.rb
lib/jekyll/tags/posts.rb
lib/jekyll/tags/replies.rb
lib/jekyll/tags/reposts.rb
lib/jekyll/tags/rsvps.rb
lib/jekyll/tags/webmentions.rb

This is purely for readability and in theory, should not affect the tag functionality.
If the longer version was originally used for performance reasons, you may close this.

Use shorter name for superclass

---

lib/jekyll/commands/webmention.rb
lib/jekyll/generators/compile_js.rb
lib/jekyll/generators/gather_webmentions.rb
lib/jekyll/generators/queue_webmentions.rb
lib/jekyll/tags/_.rb
lib/jekyll/tags/bookmarks.rb
lib/jekyll/tags/count.rb
lib/jekyll/tags/likes.rb
lib/jekyll/tags/links.rb
lib/jekyll/tags/posts.rb
lib/jekyll/tags/replies.rb
lib/jekyll/tags/reposts.rb
lib/jekyll/tags/rsvps.rb
lib/jekyll/tags/webmentions.rb
lib/jekyll/tags/webmentions_head.rb
lib/jekyll/tags/webmentions_js.rb
lib/jekyll/webmention_io.rb
lib/jekyll/webmention_io/version.rb
lib/jekyll/webmention_io/webmention.rb

Making strings immutable helps improve performance by avoiding creating new string objects on each call

Freeze string literals to improve performance

---

lib/jekyll/commands/webmention.rb
lib/jekyll/webmention_io.rb

`File.open(file, "w") { |f| YAML.dump(data, f) }` **returns a `File` object** which is not used thereafter.
The proposed utility method simply writes YAML into given file and returns `nil`

Add utility method to dump data as YAML into file

---

lib/jekyll/webmention_io.rb

..by using `attr_reader` and `attr_writer` in the module's singleton class.
(a method defined in the singleton class is same as defining the method with a `self.` prefix.)

Simplify defining getters and setters

---

lib/jekyll/tags/bookmarks.rb
lib/jekyll/tags/likes.rb
lib/jekyll/tags/links.rb
lib/jekyll/tags/posts.rb
lib/jekyll/tags/replies.rb
lib/jekyll/tags/reposts.rb
lib/jekyll/tags/rsvps.rb

The tags in the diff here have `type` of `:set_data` referring to *the same "string"* passed to `self.temlate=` which internally sets the value of `@template_name`.
With this, `:set_data` of these tags have identical definition which can be refactored away in future..

set_data in tags with @template_name as type

---

lib/jekyll/tags/_.rb

Resolves #83 
Note: `Liquid::Template.render!` is simply `render` with better error outputs..

Render in the context of the template

---

lib/jekyll/commands/webmention.rb
lib/jekyll/generators/queue_webmentions.rb
lib/jekyll/tags/_.rb
lib/jekyll/webmention_io.rb

Using `YAML.load` is a security concern when loading client-side YAML files because the contents are `eval`-ed before being loaded into memory and as such can be exploited..
Similar security concern arises when using `Kernel#open` to parse a file.

Add utility method to safely parse YAML files

---

lib/jekyll/generators/compile_js.rb
lib/jekyll/webmention_io.rb

* Declaring `private` once in the Class marks all consequent methods as `private_instance_methods`
* However, the same declaration has no effect on singleton methods

Lint use of private access modifier

---

lib/jekyll/generators/compile_js.rb
lib/jekyll/tags/webmention.rb
lib/jekyll/tags/webmentions_js.rb
lib/jekyll/webmention_io.rb
lib/jekyll/webmention_io/js_handler.rb

Resolves #99 
The rendered output of `WebmentionJSTag` is the same irrespective of given `context`. So the content can be rendered once, cached elsewhere and then retrieved from the cache for each call to the tag's `:render` method.
(This PR also involves a micro-optimization by caching array of supported_templates in the main module itself, to avoid unnecessary allocations)

Render WebmentionJSTag with a dedicated class

---

lib/jekyll/commands/webmention.rb
lib/jekyll/generators/compile_js.rb
lib/jekyll/generators/gather_webmentions.rb
lib/jekyll/generators/queue_webmentions.rb
lib/jekyll/tags/webmention.rb
lib/jekyll/tags/webmentions_js.rb
lib/jekyll/webmention_io.rb
lib/jekyll/webmention_io/js_handler.rb
lib/jekyll/webmention_io/webmention.rb

Since the constants are nested under `module Jekyll`, Ruby will resolve them without errors
(Leaving constants from Jekyll Core and plugin constants nested under `module WebmentioIO` as is for readability, even though those constants will resolve equally fine as well..)

Use shorter name for constants from plugin module

---

lib/jekyll/webmention_io.rb

Results in massive performance gains by bypassing repeated parsing of YAML files :tada:

Optimize by caching webmention data into memory

---

lib/jekyll/generators/gather_webmentions.rb
lib/jekyll/generators/queue_webmentions.rb
lib/jekyll/tags/webmentions_head.rb
lib/jekyll/webmention_io/js_handler.rb

Because `site.config["url"]` and `site.config["baseurl"]` are `nil` by default

Stringify config["url"] and config["baseurl"]

---

lib/jekyll/generators/gather_webmentions.rb
lib/jekyll/generators/queue_webmentions.rb

Nest generators under the WebmentionIO module

---

lib/jekyll/webmention_io.rb

`private` keyword is for `instance_methods`..
For `singleton_methods`, use `private_class_method` with symbols of methods as arguments

Use `private_class_method` to hide class methods

---

jekyll-webmention_io.gemspec
lib/jekyll/commands/webmention.rb
lib/jekyll/webmention_io.rb
lib/jekyll/webmention_io/webmention.rb

`after_init` hook was added in [Jekyll 3.2.0](https://github.com/jekyll/jekyll/blob/master/History.markdown#320--2016-07-26)

Drop support for outdated Jekyll versions

---

lib/jekyll/commands/webmention.rb

Since `jekyll webmention` command is going to be used separately from `jekyll build` or `jekyll serve`, we can initialize a new `Jekyll::Site` instance for the plugin's command.
Resolves #115 
P.S. @aarongustafson if you can "describe" how a sample site would look when this command is to be used, we can setup Travis to test this class as well..

Bootstrap WebmentionIO with webmention command

---

lib/jekyll/webmention_io.rb

Why:
* the calculation of age posts was always `older` no matter
the date.
This change addreses the need by:
* init timeframe variable so it will actually be properly visible
to make calculations right.

Don't classify all posts as 'older'

---

jekyll-webmention_io.gemspec
lib/jekyll/webmention_io.rb

URI.parse is deprecated in Ruby 2.7+, replaced with URI::Parser.new
Updated gemspec to require ruby 2.7+
Added kramdown to development dependencies so cucumber tests would run

Remove deprecated calls to URI.parse

---

docs/quickstart.md

Because without the page.url parameter, the webmentions include may not return anything (see: https://github.com/aarongustafson/jekyll-webmention_io/issues/155).

Quickstart: add parameter for webmentions tag

---

docs/bad_uri_policy.md
docs/configuration.md
lib/jekyll/commands/webmention.rb
lib/jekyll/webmention_io.rb

This changeset is intended to resolve #129.  Here we implement a much more flexible policy mechanism for handling URIs for which the plugin previous experienced errors sending a webmention.
Errors are classified into three different categories (unsupported, error, failure), and separate policies can be defined for each, allowing the user a lot of control over how the plugin treats these conditions.
Additionally, while the plugin currently has a feature to control retries for whole hosts, what it lacks is a mechanism to have the plugin give up on individual webmentions.
This commit introduces a new max_attempts setting which, if set, will cause the plugin to give up and mark a webmention as sent after a configured number of tries.

Implementation of new bad URI handling logic.

---

lib/jekyll/commands/webmention.rb

I don't understand the need to support sending webmentions for protocol-less links, and this code is busted: it results in the target hash table changing while we're in the middle of iterating over it (since the 'target' key value gets modified and a new has entry inserted).
If this is really needed we can always revisit later and refactor the code so it works.

Fixing a bug by breaking a feature

---

docs/configuration.md
docs/index.md
docs/syndication.md
jekyll-webmention_io.gemspec
lib/jekyll/generators/queue_webmentions.rb
lib/jekyll/webmention_io.rb

A core concept of [POSSE](https://indieweb.org/POSSE) is the syndication of content from your blog to [silos](https://indieweb.org/silo) such as Twitter, Github, and so forth.  Syndication is often done manually, but services like [Brid.gy](https://brid.gy/) make it possible to automate the process using webmentions.
To enable syndication to services supporting webmention, this PR implements  convenience configuration that makes it easy to indicate common webmention targets that you'd like to use for posts.
This implements the ideas originally discussed in issue #132 .

Syndication

---

jekyll-webmention_io.gemspec
lib/jekyll/generators/compile_js.rb
lib/jekyll/tags/webmention.rb
lib/jekyll/webmention_io.rb

While upgrading my Jekyll-build sites to Ruby 3.2, I noticed this gem is not compatible. Here’s more info, which I wrote in the commit message:
> Replacing `string_inflection` gem with `activesupport`
> 
> `string_inflection` was incompatible with Ruby `3.2`: `.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/string_inflection-0.1.2/lib/string_inflection.rb:11:in 'include': Refinement#include has been removed (TypeError)`
> 
> instead of using string_inflection's `to_singular` method, now using `ActiveSupport::Inflector.singularize`
> 
> Had to upgrade `rake` from v12 to v13 due to general dependency conflicts.
I decided to not try and update the [long-unmaintained `0.x`-version `string_inflection` gem](https://github.com/mosop/string_inflection-ruby) and instead go with the much more stable …

Ruby 3.2 support
